# Trabajo Practico n4 - Introduccion a numpy.
## Criterios de evaluación.

* Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).
* Comentarios claros y concisos que expliquen el propósito de cada sección del código.
* Utilizar mensajes de commit **descriptivos**. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE). 
* Entrega en tiempo y forma.
* Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: tp4_tlp3_nombre_apellido).
* Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter

### ¡Importante!
**El incumplimiento de los criterios de evaluación restará puntos en la nota final del práctico!**

**Importaciones:**

In [2]:
import numpy as np
from random import randint

**Actividad 1:**: Crea un array de NumPy que contenga los números del 0 al 9. (Debes utilizar un metodo de numpy para su creacion.)

In [3]:
#todo: 
primeros_numeros=np.arange(0,10,1)
print(primeros_numeros)

[0 1 2 3 4 5 6 7 8 9]


**Actividad 2:** Crea un array de 5 ceros, y luego cambia el tercer elemento (índice 2) para que sea 5. (Debes utilizar un metodo de numpy para su creacion.)

In [4]:
#todo:
five_zeros=np.zeros(5)
print(five_zeros)

five_zeros[2]=5
print(f"array de ceros con un 5 en el index 2: {five_zeros}")


[0. 0. 0. 0. 0.]
array de ceros con un 5 en el index 2: [0. 0. 5. 0. 0.]


**Actividad 3:** Genera una matriz 3x3 de números aleatorios entre 0 y 1.

In [5]:
#todo: 
np.random.rand(3,3)

array([[0.38807583, 0.62757345, 0.23195958],
       [0.18392924, 0.51510719, 0.2392698 ],
       [0.49746288, 0.83634386, 0.99322228]])

**Actividad 4:** Dado el siguiente array `arr = np.array([10, 20, 30, 40, 50])`
1. Suma 5 a cada elemento.
2. Multiplica todo por un numero aleatorio (utiliza el modulo random para generarlo.)

In [35]:
#todo:
numero_ram=randint(1,10)

print(numero_ram)
arr = np.array([10, 20, 30, 40, 50])

suma = arr + 5
multi=arr * numero_ram


print(f"Array original: {arr}")
print(f"Suma de 5 a cada elemento: {suma}")
print(f"multiplicacion por numero aleatorio: {multi}")

5
Array original: [10 20 30 40 50]
Suma de 5 a cada elemento: [15 25 35 45 55]
multiplicacion por numero aleatorio: [ 50 100 150 200 250]


**Actividad 5:** Crea una matriz identidad de tamaño 4x4 (unos en la diagonal principal y ceros en el resto).

In [7]:
#todo:
matriz_ident=np.eye(4)
print(matriz_ident)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Actividad 6:** Crea un array que comience en 0 hasta el 20, pero que solo tenga numeros pares y luego realiza las 4 operaciones basicas. (suma, resta, multiplicacion, division).

In [48]:
#todo: 
matriz_pares=np.arange(0,22,2)
print(f"array del 0 al 20 con numeros pares {matriz_pares}")

print("Suma:", np.sum(matriz_pares))
print("Resta:", np.subtract.reduce(matriz_pares))
print("Multiplicación:", np.prod(matriz_pares))




array del 0 al 20 con numeros pares [ 0  2  4  6  8 10 12 14 16 18 20]
Suma: 110
Resta: -110
Multiplicación: 0
